CREATE TABLE products (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL UNIQUE,
	`price` DOUBLE NOT NULL,
	`quantity` INT NOT NULL,
	`category` ENUM('LAPTOP', 'DESKTOP', 'SMARTPHONE', 'TABLET', 'WEARABLE', 'MONITOR', 'PRINTER', 'ACCESSORY', 'NETWORK_DEVICE'),
	`description` VARCHAR(255)
);