CREATE DATABASE IF NOT EXISTS floginfe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE floginfe;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL UNIQUE,
	`price` DOUBLE NOT NULL,
	`quantity` INT NOT NULL,
	`category` ENUM('LAPTOP', 'DESKTOP', 'SMARTPHONE', 'TABLET', 'WEARABLE', 'MONITOR', 'PRINTER', 'ACCESSORY', 'NETWORK_DEVICE'),
	`description` VARCHAR(255)
);

CREATE TABLE users (
	`id` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL
);